export type Home = Readonly<{
  address: null | string;
  albumURL: null | string;
  appointmentURL: null | string;
  area: string;
  bookingURL: null | string;
  contactHTML: string;
  crousAndGoURL: null | string;
  email: string;
  fullInformationHTML: string;
  id: string;
  images: string[];
  inHomeServices: string[];
  latitude: number;
  localServicesHTML: string;
  longitude: number;
  phone: null | string;
  shortDescription: null | string;
  title: string;
  troubleshootingURL: null | string;
  virtualVisitURL: null | string;
  websiteURL: null | string;
}>;
