export enum RestaurantKind {
  ADMINISTRATIVE_RESTAURANT = "ADMINISTRATIVE_RESTAURANT",
  APPROVED_RESTAURANT = "APPROVED_RESTAURANT",
  BREWERY = "BREWERY",
  CAFETERIA = "CAFETERIA",
  COFFEE_CORNER = "COFFEE_CORNER",
  CROUS_AND_GO = "CROUS_AND_GO",
  FOOD_TRUCK = "FOOD_TRUCK",
  GROCERY_STORE = "GROCERY_STORE",
  KIOSK = "KIOSK",
  MANAGED_RESTAURANT = "MANAGED_RESTAURANT",
  PIZZERIA = "PIZZERIA",
  RESTAURANT = "RESTAURANT",
  SANDWICH_SHOP = "SANDWICH_SHOP",
  SCOOTER = "SCOOTER",
  SELF_SERVICE = "SELF_SERVICE"
}
